import React from "react";

const TermsCondition = () => {
    return (
        <div className="text-left p-4">
            <strong>Terms &amp; Conditions</strong><br />

            <em>Last Updated as of 1<sup>st</sup> May, 2024.</em><br />

            This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.

            This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of careers.EstylishKart.com, life.EstylishKart.com &amp; blog.EstylishKart.com website.

            The use of any product, service or feature (the “Materials”) available https://EstylishKart.com (hereinafter referred to as “Website”) is owned by EstylishKart Enterprises LLP, a company incorporated under the Companies Act, 1956 with its registered office at 255/1754, Asola Extn. ,India (hereinafter referred to as “EstylishKart”).

            For the purpose of these Terms of Use, wherever the context so requires “You” or “User” shall mean any natural or legal person who visits or uses the Website. EstylishKart allows the User to surf the Website without registering on the Website. The term “We”, “Us”, “Our” shall mean EstylishKart.

            Your use of the Website and services and tools are governed by the following terms and conditions (“Terms of Use”) as applicable to the Website including the applicable policies which are incorporated herein by way of reference. Use of the Website shall subject You to the policies that are applicable to the Website. By mere use of the Website, You shall be contracting with EstylishKart and these terms and conditions including the policies constitute Your binding obligations, with EstylishKart.

            This Website, including all Materials present (excluding any applicable third party materials), is the property of EstylishKart and is copyrighted and protected by worldwide copyright laws and treaty provisions. You hereby agree to comply with all copyright laws worldwide in Your use of this Website and to prevent any unauthorized copying of the Materials. EstylishKart does not grant any express or implied rights under any patents, trademarks, copyrights or trade secret information.

            When you use any Materials provided by us through the Website you will be subject to the rules, guidelines, policies, terms and conditions applicable to such services and they shall be deemed incorporated into the ToU and considered a part and parcel of the ToU. We reserve the right, at our sole discretion, to change, modify, add, or remove portions of the ToU at any time and without any prior written notice to you. It is your responsibility to review the ToU periodically for updates/changes. Your continued use of the Website following the changes will mean that you accept and agree to the revisions. As long as you comply with the ToU, we grant you a personal, non-exclusive, non-transferable, and limited privilege to enter and use the Website.

            ACCESSING, BROWSING OR OTHERWISE USING THE WEBSITE INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF USE, SO PLEASE READ THE TERMS OF USE CAREFULLY BEFORE PROCEEDING. By impliedly or expressly accepting these Terms of Use, You also accept and agree to be bound by EstylishKart Policies (including but not limited to Privacy Policy available on Privacy Policy as amended from time to time.

            USER ELIGIBILITY

            Use of the Website is available only to persons who can form legally binding contracts under Indian Contract Act, 1872. Persons who are “incompetent to contract” within the meaning of the Indian Contract Act, 1872 including minors, un-discharged insolvents etc. are not eligible to use the Website. If you are a minor i.e. under the age of 18 years, you shall not register as a User of the Website and shall not use the website. As a minor if you wish to use the website, such use may be made by your legal guardian or parents on the Website. EstylishKart reserves the right to terminate your membership and / or refuse to provide you with access to the Website if it is brought to EstylishKart’s notice or if it is discovered that you are under the age of 18 years.

            <strong>YOUR ACCOUNT AND REGISTRATION OBLIGATIONS</strong>

            If You use the Website, You shall be responsible for maintaining the confidentiality of your Display Name and Password and You shall be responsible for all activities that occur under your Display Name and Password. You agree that if You provide any information that is untrue, inaccurate, not current or incomplete or We have reasonable grounds to suspect that such information is untrue, inaccurate, not current or incomplete, or not in accordance with this Terms of Use, We shall have the right to indefinitely suspend or terminate or block access of your membership on the Website and refuse to provide You with access to the Website.

            <strong>COMMUNICATIONS</strong>

            When You use the Website or send emails or other data, information or communication to us, You agree and understand that You are communicating with Us through electronic records and You consent to receive communications via electronic records from Us periodically and as and when required. We may communicate with you by email or by such other mode of communication, electronic or otherwise.

            <strong>CHARGES</strong>

            Membership on the Website is free. EstylishKart does not charge any fee for browsing the Website. In particular, EstylishKart may at its sole discretion introduce new services and modify some or all of the existing services offered on the Website.

            Blogs: This is to inform and clarify that individuals (including but not limited to employees of EstylishKart and referred to as “Individuals” hereafter) may contribute articles and opinions on this Website entirely at the sole discretion of EstylishKart, in the form of “blogs”, as such term is generally understood. You hereby acknowledge and agree that these blogs constitute the opinion of the Individuals in their personal capacity, and may not represent official positions of EstylishKart in any manner. EstylishKart retains all ownership and rights in these blogs.

            You may be permitted to post comments and feedback to these blogs. By doing so, You expressly agree and acknowledge to abide by the following:
            <ol>
                <li>You shall not host, display, upload, modify, publish, transmit, update or share any information which:</li>
            </ol>
            (a) belongs to another person and to which You do not have any right;

            (b) is grossly harmful, harassing, blasphemous, defamatory, obscene, pornographic, pedophilic, libelous, invasive of another’s privacy, hateful, or racially, ethnically objectionable, disparaging, relating or encouraging money laundering or gambling, or otherwise unlawful in any manner whatever; or unlawfully threatening or unlawfully harassing including but not limited to “indecent representation of women” within the meaning of the Indecent Representation of Women (Prohibition) Act, 1986;

            (c) is misleading in any way;

            (d) is patently offensive to the online community, such as sexually explicit content, or content that promotes obscenity, pedophilia, racism, bigotry, hatred or physical harm of any kind against any group or individual;

            (e) harasses or advocates harassment of another person;

            (f) involves the transmission of “junk mail”, “chain letters”, or unsolicited mass mailing or “spamming”;

            (g) promotes illegal activities or conduct that is abusive, threatening, obscene, defamatory or libelous;

            (h) infringes upon or violates any third party’s rights [including, but not limited to, intellectual property rights, rights of privacy (including without limitation unauthorized disclosure of a person’s name, email address, physical address or phone number) or rights of publicity];

            (i) promotes an illegal or unauthorized copy of another person’s copyrighted work (see “Copyright complaint” below for instructions on how to lodge a complaint about uploaded copyrighted material), such as providing pirated computer programs or links to them, providing information to circumvent manufacture-installed copy-protect devices, or providing pirated music or links to pirated music files;

            (j) contains restricted or password-only access pages, or hidden pages or images (those not linked to or from another accessible page);

            (k) provides material that exploits people in a sexual, violent or otherwise inappropriate manner or solicits personal information from anyone;

            (l) provides instructional information about illegal activities such as making or buying illegal weapons, violating someone’s privacy, or providing or creating computer viruses;

            (m) contains video, photographs, or images of another person (with a minor or an adult).

            (n) tries to gain unauthorized access or exceeds the scope of authorized access to the Website or to profiles, blogs, communities, account information, bulletins, friend request, or other areas of the Website or solicits passwords or personal identifying information for commercial or unlawful purposes from other users;

            (o) solicits gambling or engages in any gambling activity which We, in Our sole discretion, believes is or could be construed as being illegal;

            (p) interferes with another User’s use and enjoyment of the Website or any other User’s enjoyment of similar services;

            (q) refers to any website or URL that, in Our sole discretion, contains material that is inappropriate for the Website or any other website, contains content that would be prohibited or violates the letter or spirit of these Terms of Use.

            (r) harm minors in any way;

            (s) infringes any patent, trademark, copyright or other proprietary rights or third party’s trade secrets or rights of publicity or privacy;

            (t) violates any law for the time being in force;

            (u) deceives or misleads the addressee/ users about the origin of such messages or communicates any information which is grossly offensive or menacing in nature;

            (v) impersonate another person;

            (w) contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer resource; or contains any trojan horses, worms, time bombs, cancelbots, easter eggs or other computer programming routines that may damage, detrimentally interfere with, diminish value of, surreptitiously intercept or expropriate any system, data or personal information;

            (x) threatens the unity, integrity, defence, security or sovereignty of India, friendly relations with foreign states, or public order or causes incitement to the commission of any cognizable offence or prevents investigation of any offence or is insulting any other nation.

            (y) shall not be false, inaccurate or misleading;

            (z) shall not create liability for Us or cause Us to lose (in whole or in part) the services of Our internet service provider (“ISPs”) or other suppliers;
            <ol start="2">
                <li>You shall not use any “deep-link”, “page-scrape”, “robot”, “spider” or other automatic device, program, algorithm or methodology, or any similar or equivalent manual process, to access, acquire, copy or monitor any portion of the Website or any Content, or in any way reproduce or circumvent the navigational structure or presentation of the Website or any Content, to obtain or attempt to obtain any materials, documents or information through any means not purposely made available through the Website. We reserve Our right to bar any such activity.</li>
                <li>You shall not attempt to gain unauthorized access to any portion or feature of the Website, or any other systems or networks connected to the Website or to any server, computer, network, or to any of the services offered on or through the Website, by hacking, password “mining” or any other illegitimate means.</li>
                <li>You shall not probe, scan or test the vulnerability of the Website or any network connected to the Website nor breach the security or authentication measures on the Website or any network connected to the Website. You may not reverse look-up, trace or seek to trace any information on any other User of or visitor to Website, or any other customer, including any account on the Website not owned by You, to its source, or exploit the Website or any service or information made available or offered by or through the Website, in any way where the purpose is to reveal any information, including but not limited to personal identification or information, other than Your own information, as provided for by the Website.</li>
                <li>You shall not make any negative, denigrating or defamatory statement(s) or comment(s) about Us or the brand name or domain name used by Us or otherwise engage in any conduct or action that might tarnish the image or reputation, of EstylishKart or its associate companies or sellers on platform or otherwise tarnish or dilute any EstylishKart’s trade or service marks, trade name and/or goodwill associated with such trade or service marks, trade name as may be owned or used by us. You agree that You will not take any action that imposes an unreasonable or disproportionately large load on the infrastructure of the Website or EstylishKart’s systems or networks, or any systems or networks connected to EstylishKart.</li>
                <li>You agree not to use any device, software or routine to interfere or attempt to interfere with the proper working of the Website or any transaction being conducted on the Website, or with any other person’s use of the Website.</li>
                <li>You may not forge headers or otherwise manipulate identifiers in order to disguise the origin of any message or transmittal You send to Us on or through the Website or any service offered on or through the Website. You may not pretend that You are, or that You represent, someone else, or impersonate any other individual or entity.</li>
                <li>You may not use the Website or any content for any purpose that is unlawful or prohibited by these Terms of Use, or to solicit the performance of any illegal activity or other activity which infringes the rights of EstylishKart and / or others.</li>
                <li>You shall at all times ensure full compliance with the applicable provisions of the Information Technology Act, 2000 and rules thereunder as applicable and as amended from time to time and also all applicable Domestic laws, rules and regulations.</li>
                <li>Solely to enable Us to use the information You supply Us with, so that we are not violating any rights You might have in Your Information, You agree to grant Us a non-exclusive, worldwide, perpetual, irrevocable, royalty-free, sub-licensable (through multiple tiers) right to exercise the copyright, publicity, database rights or any other rights You have in Your Information, in any media now known or not currently known, with respect to Your Information. We shall be entitled to, consistent with Our Privacy Policy as adopted in accordance with applicable law, use the content or any of its elements for any type of use forever, including but not limited to promotional and advertising purposes and in any media whether now known or hereafter devised, including the creation of derivative works that may include the content You provide. You agree that any content You post may be used by us, consistent with Our Privacy Policy and Rules of Conduct on Site as mentioned herein, and You are not entitled to any payment or other compensation for such use.</li>
                <li>You shall not engage in advertising to, or solicitation of, other Users of the Website to buy or sell any products or services, including, but not limited to, products or services related to that being displayed on the https://EstylishKart.com or related to us. You may not transmit any chain letters or unsolicited commercial or junk email to other Users via the Website. It shall be a violation of these Terms of Use to use any information obtained from the Website in order to harass, abuse, or harm another person, or in order to contact, advertise to, solicit, or sell to another person other than Us without Our prior explicit consent. You understand that We have the right at all times to disclose any information (including the identity of the persons providing information or materials on the Website) as necessary to satisfy any law, regulation or valid governmental request. This may include, without limitation, disclosure of the information in connection with investigation of alleged illegal activity or solicitation of illegal activity or in response to a lawful court order or subpoena. In addition, We can (and You hereby expressly authorize Us to) disclose any information about You to law enforcement or other government officials, as we, in Our sole discretion, believe necessary or appropriate in connection with the investigation and/or resolution of possible crimes, especially those that may involve personal injury.</li>
            </ol>
            We reserve the right, but have no obligation, to monitor the materials posted on the Website. EstylishKart shall have the right to remove or edit any content that in its sole discretion violates, or is alleged to violate, any applicable law or either the spirit or letter of these Terms of Use. Notwithstanding this right, YOU REMAIN SOLELY RESPONSIBLE FOR THE CONTENT OF THE MATERIALS YOU POST ON THE WEBSITE AND IN YOUR PRIVATE MESSAGES. Please be advised that such Content posted does not necessarily reflect EstylishKart views. In no event shall EstylishKart assume or have any responsibility or liability for any Content posted or for any claims, damages or losses resulting from use of Content and/or appearance of Content on the Website. You hereby represent and warrant that You have all necessary rights in and to all Content which You provide and all information it contains and that such Content shall not infringe any proprietary or other rights of third parties or contain any libellous, tortious, or otherwise unlawful information.
            <ol start="13">
                <li>It is possible that other users (including unauthorized users or “hackers”) may post or transmit offensive or obscene materials on the Website and that You may be involuntarily exposed to such offensive and obscene materials. It also is possible for others to obtain personal information about You due to your use of the Website, and that the recipient may use such information to harass or injure You. We do not approve of such unauthorized uses, but by using the Website You acknowledge and agree that We are not responsible for the use of any personal information that You publicly disclose or share with others on the Website. Please carefully select the type of information that You publicly disclose or share with others on the Website.</li>
                <li>EstylishKart shall have all the rights to take necessary action and claim damages that may occur due to your involvement/participation in any way on your own or through group/s of people, intentionally or unintentionally in DoS/DDoS (Distributed Denial of Services).</li>
            </ol>
            Except as expressly provided in these Terms of Use, no part of the Website and no Materials may be copied, reproduced, republished, uploaded, posted, publicly displayed, encoded, translated, transmitted or distributed in any way (including “mirroring”) to any other computer, server, Website or other medium for publication or distribution or for any commercial enterprise, without EstylishKart’s express prior written consent.

            You may use Materials made available on the Website for downloading, provided that You (1) do not remove any proprietary notice language in all copies of such documents, (2) use such information only for your personal, non-commercial informational purpose and do not copy or post such information on any networked computer or broadcast it in any media, (3) make no modifications to any such information, and (4) do not make any additional representations or warranties relating to such documents.

            Third party content: The Website makes information of third parties available, including articles, analyst reports, news reports, tools to facilitate calculation, company information and data about financial markets, including any regulatory authority and other financial markets and other data from external sources (the “Third Party Content”). You acknowledge and agree that the Third Party Content is not created or endorsed by EstylishKart. The provision of Third Party Content is for general informational purposes only and does not constitute a recommendation or solicitation to purchase or sell any securities or shares or to make any other type of investment or investment decision. In addition, the Third Party Content is not intended to provide tax, legal or investment advice. You acknowledge that the Third Party Content provided to You is obtained from sources believed to be reliable, but that no guarantees are made by EstylishKart or the providers of the Third Party Content as to its accuracy, completeness, timeliness. You agree not to hold EstylishKart, any business offering products or services through the Website or any provider of Third Party Content liable for any investment decision or other transaction You may make based on Your reliance on or use of such data, or any liability that may arise due to delays or interruptions in the delivery of the Third Party Content for any reason.

            By using any Third Party Content, You may leave this Website and be directed to an external website, or to a website maintained by an entity other than EstylishKart. If You decide to visit any such site, You do so at Your own risk and it is Your responsibility to take all protective measures to guard against viruses or any other destructive elements. EstylishKart makes no warranty or representation regarding, and does not endorse, any linked Websites or the information appearing thereon or any of the products or services described thereon. Links do not imply that EstylishKart or this Website sponsors, endorses, is affiliated or associated with, or is legally authorized to use any trademark, trade name, logo or copyright symbol displayed in or accessible through the links, or that any linked site is authorized to use any trademark, trade name, logo or copyright symbol of EstylishKart or any of its affiliates or subsidiaries. You hereby expressly acknowledge and agree that the linked sites are not under the control of EstylishKart and EstylishKart is not responsible for the contents of any linked site or any link contained in a linked site, or any changes or updates to such sites. EstylishKart is not responsible for webcasting or any other form of transmission received from any linked site. EstylishKart is providing these links to You only as a convenience, and the inclusion of any link shall not be construed to imply endorsement by EstylishKart in any manner of the website.

            <strong>Posting on the Website:</strong>

            EstylishKart does not claim ownership of the materials You provide to EstylishKart (including feedback and suggestions) or post, upload, input or submit to any section of the Website, (each a “Submission” and collectively “Submissions”). However, by posting, uploading, inputting, providing or submitting (“Posting”) Your Submission You are granting EstylishKart, its affiliated companies and necessary sub-licensees permission to use Your Submission in connection with the operation of their business, including, without limitation, the license rights to: copy, distribute, transmit, publicly display, publicly perform, reproduce, edit, translate and reformat Your Submission; to publish Your name in connection with Your Submission; and the right to sublicense such rights to any other party.

            You hereby acknowledge and agree that no compensation shall be paid or no future commercial consideration has accrued with respect to the use of Your Submission by EstylishKart, as provided herein. EstylishKart shall be under no obligation to post or use any Submission You may provide and EstylishKart shall remove any Submission at any time at its own sole discretion.

            By Posting a Submission You hereby warrant and represent that You own or otherwise control all of the rights required under worldwide law for Your Submission as described in these Terms of Use including, without limitation, all the rights necessary for You to provide, post, upload, input or submit the Submissions.

            <strong>PROFANITY POLICY</strong>

            EstylishKart prohibits the use of language that is racist, hateful, sexual or obscene in nature in a public area.

            This policy extends to your Submissions, Postings and all other areas of the website that another User may view. We allow Users to ‘blur’ out the bulk of the offending word with asterisks (i.e., s*** or f***).

            Please report any violations of this policy for review.

            If a feedback comment; or any communication made between Users on the Website; or email communication between Users contain profanity, please review Our feedback removal policy and submit a request for action/removal.

            The EstylishKart application and website (“<strong>Platform</strong>”) are made available to you by EstylishKart Enterprises LLP and/or its affiliates (hereinafter may be referred to as the “<strong>Company</strong>”, “<strong>we</strong>”, “<strong>us</strong>”, and <strong>“our”</strong>) respect your privacy and is committed to protecting it through its compliance with its privacy policy. This policy amongst other things describes: (i) the type of information that the Company may collect from you when you access or use its websites, applications and other online services (hereinafter collectively referred to as the “<strong>Services</strong>”); and (ii) the Company’s practices for collecting, using, maintaining, protecting and disclosing that information.

            We encourage you to read this policy carefully to understand the Company's policies and practices regarding your information. By accessing or using its Services or its Platform, registering an account with the Company, becoming a supplier, reseller or customer on the Platform, or by attempting to become a supplier, reseller or customer, you expressly agree to be bound by the terms and conditions of this privacy policy and you are consenting to the Company's collection, use, disclosure and retention of your personal information as described here only for the sole purpose of EstylishKart.

            This policy may change from time to time, your continued use of the Company's Services after it makes any change is deemed to be acceptance of those changes, so please check the policy periodically for updates.
            <ol>
                <li><strong>Applicability of the Policy</strong></li>
            </ol>
            1.1.          This policy applies only to the information the Company collects through its Services, in email, text and other electronic communications sent through or in connection with its Services.

            1.2.          This Policy does not apply to the information that you provide to, or that is collected by, any third-party, that you use in connection with its services. The Company encourages you to consult directly with such third parties about their privacy practices.
            <ol start="2">
                <li><strong>Collection of the information</strong></li>
            </ol>
            2.1.          Some of our Services may be used without revealing any personal information, and for other Services, personal information is required. We may also collect ‘Non-Personal Information’ (i.e., information that cannot be used to identify you). Non-Personal Information includes information like the web pages that you have viewed. In order to access certain features and benefits on our Services, you may need to submit ‘Personally Identifiable Information’ i.e., information that can be used to identify you (<em>as described below</em>). Inaccurate information may affect your ability to use the Services, the information you receive when using the Services, and our ability to contact you. For example, your email address and contact number should be kept valid because these may be the primary channels through which we communicate with you. You are responsible for ensuring the accuracy of the Personally Identifiable Information you submit to the Company.

            2.2.          The Company collects several types of information from and about users of our Services, including: (i) Your Personally Identifiable Information- Personally Identifiable Information is the information that can be associated with a specific person and could be used to identify that specific person whether from that data, or from the data and other information that we have, or is likely to have access to. We do not consider Personally Identifiable Information to include information that has been made anonymous or aggregated so that it can no longer be used to identify a specific person, whether in combination with other information or otherwise. Personally Identifiable Information can include, but not be limited to, information such as your name, email address, contact number (cellular and landline), educational qualification(s), occupation, date of birth, marital status, monthly income, city and state of residence, marital status, number of children, employer details,  Aadhaar number, PAN, social security and tax identification numbers, and post-qualification or work experience among other things; and/or (ii) Information about your internet connection, the equipment you use to access our Services and your usage details.

            2.3.          We may collect this information either (i) directly from you when you provide it to us; (ii) automatically as you navigate through our Services (information collected automatically may include usage details, IP addresses and information collected through cookies, web beacons and other tracking technologies); and/or (iii) from any other source of information including from other third party sources, such as updated delivery and address information from our carriers, which we use to correct our records and deliver your next purchase more easily.

            2.4.          Information you provide to us.

            2.4.1. Your account information: Your full name, email address, postal code, password and other information you may provide with your account, such as your gender, mobile phone number and website. Your profile picture (if any) that will be publicly displayed as part of your account profile. You may optionally provide us with this information through third-party sign-in services such as Facebook and Google Plus. In such cases, we fetch and store whatever information is made available to us by you through these sign-in services.

            2.4.2. Your preferences: Your preferences and settings such as time zone and language.

            2.4.3. Your content: Information you provide through our Services, including your reviews, photographs, comments, lists, followers, the users you follow, ordering details and history, favourite categories, special requests, contact information of people you add to, or notify of, your orders through our Services, names, and other information you provide on our Services, and other information in your account profile.

            2.4.4. Your searches and other activities: The search terms you have looked up and results you selected.

            2.4.5. Your browsing information: How long you used our Services and which features you used; the ads you clicked on.

            2.4.6. Your communications: Communications between you and other users or suppliers through our Services; your participation in a survey, poll, sweepstakes, contest or promotion scheme; your request for certain features (e.g., newsletters, updates or other products); your communication with us about employment opportunities posted to the Services.

            2.4.7. Your transactional information: If you make use of our Services, we may collect and store information about you to process your requests and automatically complete forms for future transactions, including (but not limited to) your name, phone number, gender, transaction details, PAN number, device type, Platform usage details, address, email, billing information and credit or payment card information or other payment related details. This information may be shared with third parties which assist in processing and fulfilling your requests, including PCI compliant payment gateway processors and credit information companies. If you write reviews about businesses with which you conduct transactions through our Services, we may publicly display information that you transacted with those businesses.

            2.4.8. Your Public Posts: You also may provide information (such as ratings, reviews, tips, photos, comments, likes, bookmarks, friends, lists, etc.) to be published or displayed (hereinafter, “<strong>posted</strong>”) on publicly accessible areas of our Services or transmitted to other users of our Services or third parties (hereinafter collectively referred to as “<strong>User Contributions</strong>”). Your User Contributions are posted on and transmitted to others at your own risk. Please be aware that no security measures are perfect or impenetrable (see the "Security" section below). Additionally, we cannot control the actions of other users of our Services with whom you may choose to share your User Contributions. Therefore, we cannot and do not guarantee that your User Contributions will not be viewed by unauthorized persons. We may display this information on the Services, share it with businesses, and further distribute it to a wider audience through third party sites and services. You should be careful about revealing any sensitive details about yourself in such postings.

            2.4.9. We use the information you provide to us to analyse and enhance the functionality and improve the quality of our Services, and to personalize your experience while using our Services. We also use this information to display relevant advertising, provide services to you, provide support to you, communicate with you, and comply with our legal obligations.

            2.5.    Information we may automatically collect include but may not be limited to the following.

            2.5.1. We may automatically collect certain information about the computer or devices (including mobile devices) you use to access the Services, and about your use of the Services, even if you use the Services without registering or logging in.

            2.5.2. Usage information: Details of your use of our Services, including traffic data, location data, logs and other communication data and the resources that you access and use on or through our Services.

            2.5.3. Computer and device information: Information about your computer, Internet connection and mobile device, including your IP address, operating systems, platforms, browser type, other browsing information (connection, speed, connection type etc.), device type, device's unique device identifier, mobile network information and the device's telephone number.

            2.5.4. Stored information and files: Our Services also may access metadata and other information associated with other files stored on your mobile device. This may include, for example, photographs, audio and video clips, personal contacts and address book information.

            2.5.5. Location information: Our applications collect real-time information about the location of your device, as permitted by you.

            2.5.6. Last URL visited: The URL of the last web page you visited before visiting our websites.

            2.5.7. Mobile device IDs: Unique mobile device identifier (e.g. IDFA, GAID or other device IDs on Apple devices like the iPhone and iPad), if you're using our Services on a mobile device, we may use mobile device IDs (the unique identifier assigned to a device by the manufacturer), instead of cookies, to recognize you. We may do this to store your preferences and track your use of our applications. Unlike cookies, mobile device IDs cannot be deleted. Advertising companies may use device IDs to track your use of our applications, track the number of advertisements displayed, measure advertising performance and display advertisements that are more relevant to you. Analytics companies may use mobile device IDs to track your usage of our applications.

            2.5.8. Your preferences: Your preferences and settings such as time zone and language.

            2.5.9. Your activity on the Services: Information about your activity on the Services, such as your search queries, comments, domain names, search results selected, number of clicks, pages viewed and the order of those pages, how long you visited our Services, the date and time you used the Services, error logs, and other similar information.

            2.5.10.    Mobile status: For mobile application users, the online or offline status of your application.

            2.5.11.    Applications: If you use the Company’s application, the Company may collect information about the presence and/ or absence and/or details pertaining to other applications on your mobile phone. The applications we gather information for, may vary across categories including, without limitation, shopping, fashion, food and travel. This will help us understand you and your preferences better and enable the Company to provide you with a personalized experience. We may collect, process and store your user ID associated with any social media account (such as your Facebook and Google account) that you use to sign into the Services or connect with or use with the Services. Please see your social media provider's privacy policy and help center for more information about how they share information when you choose to connect your account.

            2.6 You may withdraw the consent provided to us to collect and use your personal information by writing to the designated Grievance Officer as provided in Section 14 of this Privacy Policy. However, in case of withdrawal of such consent, we may not undertake the activities for which the information was sought.
            <ol start="3">
                <li><strong>Use of the information</strong></li>
            </ol>
            We use the information we collect from and about you for a variety of purposes, including:

            3.1.         For purchase and delivery of products and services. We use your personal information to take, handle and fulfil orders, deliver products and services, process payments, and communicate with you about orders, products and services, and promotional offers.

            3.2.          To provide, troubleshoot, and improve the Services. We use your personal information to provide functionality, analyse performance, fix errors, and improve the usability and effectiveness of the Services.

            3.3.        For recommendations and personalization. We use your personal information to recommend features, products, and services that might be of interest to you, identify your preferences, and personalize your experience with the Services. We may also share your preferences, or the Services availed by you with your network followers on the Company for marketing and other promotional activities of our Services

            3.4.         To comply with legal obligations. In certain cases, we collect and use your personal information to comply with laws. For instance, we collect from sellers, information regarding place of establishment and bank account information for identity verification and other purposes.

            3.5.         To Communicate with you. We use your personal information to communicate with you in relation to the Services via different channels (e.g., by phone, e-mail, chat).

            3.6.          For advertising. We use your personal information to display interest-based ads for features, products, and services that might be of interest to you. We do not use information that personally identifies you to display interest-based ads.

            3.7.        For Fraud Prevention and Credit Risks. We use personal information to prevent and detect possibility of non-payment, fraud, and abuse in order to protect the security of our users, the Company, and others. We may also, directly or through a third party (including CICs), use scoring methods to assess and manage credit risks, including by way of sharing the result of said scoring methods with relevant third parties, payment gateways, financial institutions.

            3.8.          To administer contests and sweepstakes.

            3.9.          To carry out Company’s obligations and enforcing rights arising from any contracts entered into between you and the Company, including for billing and collection.

            3.10.      Research. Generating and reviewing reports and data, and to conduct research on the Company’s user base and service usage patterns. To conduct research following internal review protocols to ensure the balancing of privacy and to use anonymized data for research. Use for internal purposes such as auditing. understand our users (what they do on our Services, what features they like, how they use them, etc.), improve the content and features of our Services (such as by personalizing content to your interests), process and complete your transactions, and make special offers

            3.11.      To fulfil any other purpose for which you provide us the information and/or for any other purpose with your consent.

            3.12    To check your eligibility for certain products/services including but not limited to credit and payment products and provide access to the services being offered by us, our affiliates, banks, financial institutions or our lending partners.
            <ol start="4">
                <li><strong>Sharing of the information</strong></li>
            </ol>
            4.1.    We may disclose personal information that we collect, or you provide, as described in this privacy policy, in the following ways:

            4.1.1.      General Information Disclosures
            <ol>
                <li>To our holding companies, subsidiaries and affiliates, which are entities under common ownership or control of the Company.</li>
                <li>To contractors, advertisers/service providers, credit information agencies, analytics and research partners, other banks or financial institutions, insurers or intermediaries and other third parties whom we use to support our business (e.g. logistics and delivery, to collect payments), or to improve your experience on our platform and who are bound by contractual obligations to keep personal information confidential and use it only for the purposes for which we disclose it to them.</li>
                <li>To a buyer or other successor in the event of a merger, divestiture, restructuring, reorganization, dissolution or other sale or transfer of some or all of the Company's assets, whether as a going concern or as part of bankruptcy, liquidation or similar proceeding, in which personal information held by the Company about the users of our Services are among the assets transferred.</li>
                <li>To third parties to market their products or services to you which we feel may be of interest or beneficial to you.                                                                                                  We contractually require these third parties to keep personal information confidential and use it only for the purposes for which we disclose it to them.</li>
            </ol>
            4.1.2.      To fulfil the purpose for which you provide it.

            4.1.3.      For any other purpose disclosed by us when you provide the information.

            4.2.    Service Providers. We may share your information with outside vendors that we use for a variety of purposes, such as to send you communications via emails, messages or tele-call to inform you about the services and/or products  that may be of interest to you, push notifications to your mobile device on our behalf, provide voice recognition services to process your spoken queries and questions, help us analyze use of our Services, process and collect payments, help us diversify the payment processing and collection methods available, and offer you special offers and services where available. Some of our products, services and databases are hosted by third party hosting services providers. We also may use vendors for other projects, such as conducting surveys, organizing sweepstakes for us, advertising, marketing and advertisement measuring purposes. We may share information about you with these vendors only to enable them to perform their services.

            4.3.   Credit Analysis. You hereby authorize and expressly consent for us to share your personal information with third parties, which may include Credit Information Companies ("CIC") to do an aggregate check of your credit profile for trying to make a wider variety of payment options available for you, some of which options may depend on the result of your credit analysis. Your credit score and/or credit information report (together “Credit Information”) will be obtained on your behalf, through a 'soft enquiry’ from the relevant CIC and we have no control over the content or accuracy of information provided in your Credit Information by CIC. We get this information from CICs for and on your behalf only when you agree to appoint us as your lawfully appointed authorized agent/representative for collecting your Credit Information from CICs. By consenting to use and avail your credit information report through us, you agree that we and the CICs shall be entitled to rely on your authorization and consent granted by you to us. You also consent to the sharing of your Credit Information with third parties by the CIC or us, for the purpose of checking your eligibility to avail of additional payment options and/or any other special offers.

            4.4  Legal Purposes. We may share your information when we believe in good faith that such sharing is reasonably necessary in order to investigate, prevent, or take action regarding possible illegal activities or to comply with legal process. We may also share your information to investigate and address threats or potential threats to the physical safety of any person, to investigate and address violations of this Privacy Policy or the Company’s Terms of Service, or to investigate and address violations of the rights of third parties and/or to protect the rights, property and safety of the Company, our employees, users, or the public. This may involve the sharing of your information with law enforcement, government agencies, courts, and/or other organizations on account of legal requests such as subpoena, court order or government demand to comply with the law.

            4.4.    Social Networks. If you interact with social media features on our Services, such as the Facebook Like button, or use your social media credentials to log-in or post content, these features may collect information about your use of the Services, as well as post information about your activities on the social media service. Your interactions with social media companies are governed by their privacy policies.

            4.5.    To enforce or apply our Terms of Use available at https://EstylishKart.com and other agreements, including for billing and collection purposes.

            4.6.    If we believe disclosure is necessary or appropriate to protect the rights, property, or safety of the Company, our users or others. This includes exchanging information with other companies and organizations for the purposes of fraud protection and credit risk reduction of the Company, our users, our service providers, our payment processing partners etc.

            4.7.    Consent. We may share your information in any other circumstances where we have your consent.
            <ol start="5">
                <li><strong>Third Party links and services</strong></li>
            </ol>
            5.1.          The Services may contain links to third-party websites. Your use of these features may result in the collection, processing or sharing of information about you, depending on the feature. Please be aware that we are not responsible for the content or privacy practices of other websites or services which may be linked on the Company’s Services. We do not endorse or make any representations about third-party websites or services. Our Privacy Policy does not cover the information you choose to provide to or that is collected by these third parties. We strongly encourage you to read such third parties' privacy policies.
            <ol start="6">
                <li><strong>Anonymous or de-identified data</strong></li>
            </ol>
            6.1.          We may anonymize and/or de-identify information collected from you through the Services or via other means, including via the use of third-party web analytic tools as described below. As a result, our use and disclosure of aggregated and/or de-identified information is not restricted by this Privacy Policy, and it may be used and disclosed to others without limitation.
            <ol start="7">
                <li><strong>Cookies</strong></li>
            </ol>
            7.1.          Cookies are alphanumeric identifiers with a small amount of data that is stored on the user’s device hard-drive containing information about the user, commonly used as an anonymous unique identifier. We may offer certain features only through ‘cookies’ and may also collect information about you using these cookies. Please note, a cookie in no way gives the Company access to your device. Other websites may place their own cookies or other files on your device, collect data or solicit personal information from you, for which the Company shall not be held responsible or liable. We encourage you to read the privacy policies of all external sites. We also use cookies from third party partners for marketing and promotional purposes. Please note that most web browsers are set to accept cookies by default.

            7.2.          We strive to provide you with choices regarding the personal information you provide to us.
            <ol start="8">
                <li><strong>Security Precautions</strong></li>
            </ol>
            8.1.          We ensure to maintain reasonable physical, electronic, and managerial procedures to safeguard and help prevent unauthorized access to your information and to maintain data security. These safeguards take into account the sensitivity of the information that we collect, process and store and the current state of technology. We follow generally accepted industry standards to protect the personal information submitted to us, both during transmission and once we receive it. The access to the Services is offered through the use of a secure server and adhere to our security guidelines to protect it against unauthorized access. However, by using the Services, the users accept the inherent security implications of data transmission over the internet and the World Wide Web which cannot always be guaranteed as completely secure, and therefore, there would always remain certain inherent risks regarding use of the Services.

            8.2.          We assume no liability or responsibility for disclosure of your information due to errors in transmission, unauthorized third-party access, or other causes beyond our control. You play an important role in keeping your personal information secure. You should not share your username, password, or other security information for your account with anyone. If we receive instructions using your username and password, we will consider that you have authorized the instructions for such use.
            <ol start="9">
                <li><strong>Permissible Age</strong></li>
            </ol>
            9.1.          The Services are not intended for users under the age of 18 (eighteen), unless permitted under applicable local laws (Permissible Age). We do not knowingly collect any personal information from users or market to or solicit information from anyone under the age of 18 and use of our Services is available only to persons who can form a legally binding contract under the Indian Contract Act, 1872.

            9.2.          If you are under the age of 18 years then you must use the Services under the supervision of your parent, or legal guardian. If we become aware that a person submitting personal information is under the age of 18 years, we will delete the account and any related information as soon as possible.
            <ol start="10">
                <li><strong>Data Retention</strong></li>
            </ol>
            10.1.         A user can close an account by visiting the profile settings page on our website. A user may request for deletion of its personal information by raising a request with the Grievance Officer as per the provisions of Section 14 of this Privacy Policy. Notwithstanding the foregoing, we reserve the right to retain your personal information in accordance with applicable laws, for a period no longer than is required for the purpose for which it was collected or as required under any applicable law. We may retain information about you for the purposes authorized under this Privacy Policy unless prohibited by law. Thereafter, we will either delete your personal information or de-identify it so that it is anonymous and not attributed to your identity. We may archive information to prevent, investigate, or identify possible wrongdoing in connection with the Service or to comply with legal obligations. We may also continue to retain your data in anonymised form for analytical and research purposes.
            <ol start="11">
                <li><strong>Job Applicants</strong></li>
            </ol>
            11.1.      If your information is submitted to us through our Service when applying for a position with the Company, the information will be used to consider your application. We may retain your information for any period of time. This information may be shared with other companies for the purpose of evaluating your qualifications for the particular position or other available positions, as well as with third-party service providers retained by us to collect, maintain and analyze candidate submissions for job postings.
            <ol start="12">
                <li><strong>Your Consent</strong></li>
            </ol>
            12.1.      By accessing or using the Services or by providing your information, you consent to the collection, use, storage, disclosure and otherwise processing of your information (including sensitive personal information) on the Services in accordance with this Privacy Policy. If you disclose to us any personal information relating to other people, you represent that you have the authority to do so and to permit us to use the information in accordance with this Privacy Policy.

            12.2.      You, while providing your personal information in relation to the Services or any partner platforms or establishments, consent to us (including our other corporate entities, affiliates, lending partners, CIC’s, technology partners, marketing channels, business partners and other third parties) to contact you through SMS, instant messaging apps, call and/or e-mail for the purposes specified in this Privacy Policy.
            <ol start="13">
                <li><strong>Changes to this Privacy policy</strong></li>
            </ol>
            13.1.      We reserve the right to amend this Privacy Policy from time to time to reflect changes in the law, our data collection and use practices, the features of our services, or advances in technology. Please check this page periodically for changes. Use of information we collect is subject to the Privacy Policy in effect at the time such information is used. If we make any material changes to this Privacy Policy, we will post the changes here. Please review the changes carefully. Your continued use of the Services following the posting of changes to this Privacy Policy will constitute your consent and acceptance of those changes.
            <ol start="14">
                <li><strong>Grievance Officer</strong></li>
            </ol>
            14.1.      In accordance with Information Technology Act, 2000 and the Information Technology (Reasonable Security Practices and Procedures and Sensitive Personal Data or Information) Rules, 2011, the name and contact details of the Grievance Officer are provided below:

            Grievance Officer

            Address – 255/1754, Asola Extn, Fatehpur, New Delhi - 110074

            Email id: <a href="mailto:legal@EstylishKart.com">legal@EstylishKart.com</a>

            Time: Mon – Fri  (10:00AM to 5:00PM)
            <ol start="15">
                <li><strong>Contact us</strong></li>
            </ol>
            15.1.      If you have any queries relating to the processing/ usage of information provided by you or the Company's Privacy Policy or if you would like to raise any other inquiries, you may email us at the contact information provided above under section 14 of this privacy policy.

            <strong>DISCLAIMER OF WARRANTIES AND LIABILITY</strong>

            This Website, all the Materials and information/content (including but not limited to software) and services, included on or otherwise made available to You through this website are provided on “as is” and “as available” basis without any representation or warranties, express or implied except otherwise specified in writing. Without prejudice to the forgoing paragraph, EstylishKart does not warrant that:
            <ul>
                <li>This Website will be constantly available, or available at all; or</li>
                <li>The information on this Website is complete, true, accurate or non-misleading.</li>
            </ul>
            EstylishKart will not be liable to You in any way or in relation to the Materials of, or use of, or otherwise in connection with, the Website. EstylishKart does not warrant that this site; information, content, Materials, product (including software) or services included on or otherwise made available to You through the Website; their servers; or electronic communication sent from Us are free of viruses or other harmful components.

            <strong>INDEMNITY</strong>

            You shall indemnify and hold harmless EstylishKart, its owner, licensee, affiliates, subsidiaries, group companies (as applicable) and their respective officers, directors, agents, and employees, from any claim or demand, or actions including reasonable attorneys’ fees, made by any third party or penalty imposed due to or arising out of Your breach of this Terms of Use, privacy Policy and other Policies, or Your violation of any law, rules or regulations or the rights (including infringement of intellectual property rights) of a third party.

            <strong>LIMITATION OF DAMAGES</strong>

            In no event shall EstylishKart or any of its subsidiaries or affiliates be liable to any entity for any direct, indirect, special, consequential or other damages (including, without limitation, any lost profits, business interruption, loss of information or programs or other data on your information handling system) that are related to the use of, or the inability to use, the content, materials, and functions of this Website or any linked Website, even if EstylishKart is expressly advised of the possibility of such damages.

            <strong>DISCLAIMER</strong>

            The Website may contain inaccuracies and typographical and clerical errors. EstylishKart expressly disclaims any obligation(s) to update this Website or any of the materials on this website. EstylishKart does not warrant the accuracy or completeness of the Materials or the reliability of any advice, opinion, statement or other information displayed or distributed through the Website. You acknowledge that any reliance on any such opinion, advice, statement, memorandum, or information shall be at your sole risk. EstylishKart reserves the right, in its sole discretion, to correct any errors or omissions in any portion of the Website. EstylishKart may make any other changes to the Website, the materials and the products, programs, services or prices (if any) described in the Website at any time without notice. This Website is for informational purposes only and should not be construed as technical advice of any manner.

            <strong>APPLICABLE LAW</strong>

            Terms of Use shall be governed by and interpreted and construed in accordance with the laws of India. The place of jurisdiction shall be exclusively in Delhi.

            <strong>CONTACT US</strong>

            Please contact us at legal@EstylishKart.com for any questions or comments (including all inquiries unrelated to copyright infringement) regarding this Website policy.
        </div>
    )
}

export default TermsCondition;